version: '2'
services:
# Nginx proxy pass frontends
    search_frontend:
        container_name: search_frontend
        image: nginx
        links:
            - searchsite
#            - search_uploadstatus:statusbackend
        volumes_from:
            - searchsite
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d:ro
            - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
            - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
        ports:
            - 80:80

# Search testing
    searchsite:
        container_name: searchsite
        build:
            context: ./docker/searchsite
        volumes:
            - ./docker/searchsite/php.ini:/usr/local/etc/php/php.ini:ro
            # - ./docker/searchsite/fpm-options.conf:/usr/local/etc/php-fpm.d/fpm-options.conf
            - ./application:/var/www/html
        links:
            - search_metadataserver:metadata
            - search_policyserver:policy
            - search_sitedb:sitedb
            - search_elasticdb:elasticdb
        environment:
            CORS_ENABLED: 1
            TIMEZONE: America/Los_Angeles
            METADATA_PORT: tcp://metadata:8121
            POLICY_PORT: tcp://policy:8181
            SITEDB_ADDR: sitedb
            SITEDB_PORT: 5432
            SITEDB_USER: search
            SITEDB_PASSWORD: search
            SITEDB_DB_NAME: search
            SITEDB_DBDRIVER: postgre
            XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
            GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
            PHP_IDE_CONFIG: serverName=PacificaSearch
        ports:
            - 9000:9000

    search_sitedb:
        container_name: search_sitedb
        image: postgres
        environment:
            POSTGRES_PASSWORD: search
            POSTGRES_DB: search
            POSTGRES_USER: search
        ports:
            - 55432:5432

# Metadata and policy servers
    search_elasticdb:
#      container_name: search_elasticdb
#      image: cagataygurturk/docker-ssh-tunnel
#      volumes:
#        - $HOME/.ssh/tunnel-config:/root/.ssh/config:ro
#        - $HOME/.ssh/tunnel_id_ecdsa:/root/.ssh/tunnel_id_ecdsa:ro
#      ports:
#        - 9201:9201
#      environment:
#        ELASTICDB_PORT: tcp://elasticdb:9200
#        TUNNEL_HOST: pacifica-tunnel
#        REMOTE_HOST: esmaster-dev.my.emsl.pnl.gov
#        LOCAL_PORT: 9200
#        REMOTE_PORT: 9200


      build:
        context: ../metadata
        dockerfile: docker-compose/Dockerfile.elastic
      container_name: search_elasticdb
      ports:
          - 9201:9201
      environment:
        - cluster.name=pacifica-cluster
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1

    search_metadatadb:
        image: postgres
        container_name: search_metadatadb
        environment:
            POSTGRES_PASSWORD: pacifica
            POSTGRES_DB: pacifica_metadata
            POSTGRES_USER: pacifica
        ports:
            - 5432:5432

#  SSH TUNNEL DOCKER CONFIGS

    search_metadataserver:
      container_name: search_metadataserver
      image: cagataygurturk/docker-ssh-tunnel
      volumes:
        - $HOME/.ssh:/root/ssh:ro
#        - $HOME/.ssh/tunnel-config:/root/.ssh/config:ro
#        - $HOME/.ssh/tunnel_id_ecdsa:/root/.ssh/tunnel_id_ecdsa:ro
#      ports:
#        - 8121:8121
      environment:
        ELASTICDB_PORT: tcp://elasticdb:9200
        TUNNEL_HOST: pacifica-tunnel
        REMOTE_HOST: core-0-dev.my.emsl.pnl.gov
        LOCAL_PORT: 8121
        REMOTE_PORT: 7121

    search_policyserver:
      container_name: search_policyserver
      image: cagataygurturk/docker-ssh-tunnel
      volumes:
        - $HOME/.ssh:/root/ssh:ro
#        - $HOME/.ssh/tunnel-config:/root/.ssh/config:ro
#        - $HOME/.ssh/tunnel_id_ecdsa:/root/.ssh/tunnel_id_ecdsa:ro
#      ports:
#        - 8181:8181
      environment:
        ELASTICDB_PORT: tcp://elasticdb:9200
        TUNNEL_HOST: pacifica-tunnel
        REMOTE_HOST: core-0-dev.my.emsl.pnl.gov
        LOCAL_PORT: 8181
        REMOTE_PORT: 8181

# END SSH TUNNEL DOCKER CONFIGS


#    search_metadataserver:
#        build:
#            context: ../metadata
#            dockerfile: Dockerfile
#        container_name: search_metadataserver
#        links:
#            - search_metadatadb:postgres
#            - search_elasticdb:elasticdb
#        ports:
#            - 8122:8121
#        environment:
#            ELASTICDB_PORT: tcp://elasticdb:9200
#            POSTGRES_ENV_POSTGRES_DB: pacifica_metadata
#            POSTGRES_ENV_POSTGRES_USER: pacifica
#            POSTGRES_PORT_5432_TCP_ADDR: postgres
#            POSTGRES_PORT_5432_TCP_PORT: 5432
#            POSTGRES_ENV_POSTGRES_PASSWORD: pacifica
#
#    search_policyserver:
#        build:
#            context: ../policy
#            dockerfile: Dockerfile
#        container_name: search_policyserver
#        restart: unless-stopped
#        links:
#            - search_metadataserver:metadata
#        ports:
#            - 8181:8181
#        environment:
#            METADATA_PORT: tcp://metadata:8121


#    search_uploadstatus:
#      container_name: search_uploadstatus
#      build:
#        context: ../upload-status
#        dockerfile: Dockerfile.dev
#      # image: pacifica/upload-status
#      volumes:
#        - ../upload-status/:/var/www/html
#      links:
#        - search_metadataserver:metadata
#        - search_policyserver:policy
#        - search_uploadstatusdb:cartdb
#        # - archiveinterface:archivei
#        - ingestserver:ingest
#      environment:
#        UPLOAD_STATUS_ADDR: statusbackend
#        UPLOAD_STATUS_PORT: 80
#        METADATA_PORT: tcp://metadata:8121
#        POLICY_PORT: tcp://policy:8181
#        ARCHIVE_PORT: tcp://archivei:8080
#        CART_PORT: tcp://cart:8081
#        INGESTER_PORT: tcp://ingest
#        CARTDB_ADDR: cartdb
#        CARTDB_PORT: 5432
#        CARTDB_USER: pacifica
#        CARTDB_PASSWORD: pacifica
#        CARTDB_DB_NAME: pacifica_upload_status
#        CARTDB_DBDRIVER: postgre
#        CART_DOWNLOAD_PORT: tcp://cartng.emsl.pnl.gov:8443
#        FILE_DOWNLOAD_PORT: tcp://filesng.emsl.pnl.gov:8443
#        SITE_NAME: status.local
#
#    search_uploadstatusdb:
#      container_name: search_uploadstatusdb
#      image: postgres
#      environment:
#        POSTGRES_PASSWORD: pacifica
#        POSTGRES_DB: pacifica_upload_status
#        POSTGRES_USER: pacifica
#      ports:
#        - 45432:5432
#
#    ingestserver:
#      container_name: search_ingest
#      image: nginx:alpine
#      volumes:
#        - ../reporting/ingest_data:/usr/share/nginx/html
#        - ../reporting/auth/ingest_conf:/etc/nginx/conf.d
#      # ports:
#      #   - 9080:9080